spring:
  output:
    ansi:
      enabled: always

#######################################################
# Application Specific configuration
#######################################################
wx:
  api:
      access-token: https://wxapi.weixin.qq.com/cgi-bin/token
      template-message: https://wxapi.weixin.qq.com/cgi-bin/message/wxopen/template/send
  mini-program:
    grantType: authorization_code
    authUrl: https://wxapi.weixin.qq.com/sns/jscode2session


---
spring:
  profiles: dev

logging:
  level:
    root: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: INFO
    org.springframework.security: INFO
    org.springframework.boot.actuate.endpoint.web.servlet: INFO
    org.springframework.boot.autoconfigure: ERROR